apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: sb9r8240q-python 
  janus-idp.io/tekton: sb9r8240q-python
  backstage.io/kubernetes-id: sb9r8240q-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sb9r8240q-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml